name: Sync Kaggle with GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Her gün çalıştırır (Zamanlamayı değiştirebilirsiniz)

jobs:
  kaggle_sync:
    runs-on: ubuntu-latest

    steps:
      # Repository'i klonla
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Kaggle API anahtarını yükle
      - name: Set up Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Kaggle'dan veri çek
      - name: Download Kaggle Dataset or Notebook
        run: |
          kaggle datasets download -d <dataset-ismi> --unzip
          # Eğer bir notebook istiyorsanız:
          # kaggle kernels pull <kernel-ismi>

      # Değişiklikleri commit et ve GitHub'a yükle
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync Kaggle Data"
          git push
