name: Sync Kaggle Notebooks to GitHub

on:
  schedule:
    # Belirli aralıklarla çalışacak şekilde zamanlanmış görev
    - cron: '0 0 * * *'  # Her gün gece yarısı çalışır
  workflow_dispatch:
    # Manuel olarak çalıştırılabilir
  push:
    branches:
      - main  # main branch'inde push yapıldığında tetiklenir

jobs:
  sync_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Kaggle API Key
        run: |
          echo "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Install dependencies
        run: |
          pip install kaggle  # Kaggle API'sini yükleyin
          pip install gitpython  # Git işlemleri için gitpython

      - name: Sync Kaggle notebooks
        run: |
          mkdir -p notebooks  # Notebooks dizini oluşturuluyor
          kaggle kernels pull -u  # Tüm kullanıcı kernel'larını indir
          
          # Git işlemleri
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add ./notebooks
          git commit -m "Sync Kaggle notebooks"
          git push origin main  # GitHub'a yükleme
