name: Kaggle Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-kaggle:
    runs-on: ubuntu-latest

    steps:
      # Repository'yi checkout yap覺yoruz
      - name: Checkout repository
        uses: actions/checkout@v4

      # Kaggle API key'i environment variable olarak ekliyoruz
      - name: Set up Kaggle API key
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Kaggle veri setini indiriyoruz
      - name: Download dataset from Kaggle
        run: |
          kaggle datasets download -d <DATASET_NAME>  # Burada veri setinin ismini yazmal覺s覺n
          
      # Alternatif olarak, dataset'i bir zip dosyas覺 olarak indirebilirsin
      - name: Unzip Kaggle dataset
        run: |
          unzip <DATASET_NAME>.zip -d ./dataset
