name: Sync Kaggle Notebooks to GitHub

on:
  schedule:
    # Her gün gece 12'de çalışacak şekilde ayarlanmış cron job
    - cron: '0 0 * * *'  
  workflow_dispatch:  # Manuel olarak da çalıştırılabilir
  push:
    branches:
      - main  # main branch'inde push yapıldığında tetiklenir

jobs:
  sync_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # GitHub repository'sine erişim sağlama

      - name: Set up Kaggle API Key
        run: |
          mkdir -p ~/.kaggle  # .kaggle dizini oluşturuluyor
          echo "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json  # Kaggle API anahtarı ekleniyor
          chmod 600 ~/.kaggle/kaggle.json  # Anahtarın erişim izinlerini ayarlama

      - name: Install dependencies
        run: |
          pip install kaggle  # Kaggle API'si kuruluyor
          pip install gitpython  # Git işlemleri için gitpython kütüphanesi

      - name: Sync Kaggle notebooks
        run: |
          mkdir -p notebooks  # Notebooks klasörü oluşturuluyor
          kaggle kernels pull -u  # Kullanıcıya ait tüm kernel'lar indiriliyor
          
          # Git işlemleri
          git config --global user.name "GitHub Actions"  # Git kullanıcı adı ayarlama
          git config --global user.email "actions@github.com"  # Git e-posta adresi ayarlama
          
          git add ./notebooks  # Notebooks klasöründeki dosyaları git'e ekleme
          git commit -m "Sync Kaggle notebooks"  # Commit mesajı
          git push origin main  # GitHub'a push işlemi
